
PROCESS_NAME_SET = None
PROCESS_DATA = None
SERVICE_NAME_SET = None
SYSPATH_STR = None
SYSPATH_FILE_SET = None
SYSTEMROOT_STR = None
SYSTEMROOT_FILE_SET = None
DRIVERPATH_STR = None
DRIVERPATH_FILE_SET = None
DRIVERPATH_DATA = None
PROFILE_PATH = None
USER_DIRS_LIST = None
HKEY_USERS_DATA = None
PROGRAM_FILES_STR = None
PROGRAM_FILESX86_STR = None
ENV_VARS = None