@echo off
echo USERID=%1/%2
echo BUFFER=30720
echo FILE=dc32.tmp
echo COMPRESS=N
echo GRANTS=N
echo INDEXES=%3
echo ROWS=N
echo CONSTRAINTS=%3
echo FULL=N
echo RECORDLENGTH=30720
echo RECORD=N
echo DIRECT=N
echo FEEDBACK=2000
